#!/bin/sh

# 
# ~/.vnc/xstart for ubuntu 16 gnome
# 

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
vncconfig -iconic &
x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
gnome-session &
gnome-panel &
gnome-settings-daemon &
metacity &
nautilus &
